In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans:- As we cas see data type of list_ is list and array_list is array

In [4]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]

In [6]:
list_

['1', '2', '3', '4', '5']

In [7]:
type(list_)

list

In [8]:
array_list = np.array(object = list_)

In [9]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [10]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [11]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]

In [12]:
for i in list_:
    print(type(i))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
array_list = np.array(object = list_)

In [14]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Ans :- yes there is difference in data types of the elements present in list_ and array_list'

In [15]:
array_list = np.array(object = list_, dtype = int)

In [16]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [17]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]

In [19]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


The elements in array_list is of type int and in list_ is of data type str

Consider the below code to answer further questions:
    
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [20]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [21]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
num_array.shape

(2, 3)

In [23]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [27]:
array1=np.zeros([3,3])

In [28]:
array1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
array1.size

9

In [30]:
array1.shape

(3, 3)

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])